### ISSUE TITLE
issue installing package

### ISSUE THREAD

**Issue by caterinagregorio** [davidbolin/ngme#1]
Hello,
I am trying to install the package but it fails to compile, is the package active?

**Comment by davidbolin** [comment]
Hi, can you please let us know which system you are compiling on, as well as the error message?

**Comment by caterinagregorio** [comment]
Thanks for your reply, I was compiling on Windows, tried again this morning and it now worked on both my computers

**Comment by davidbolin** [comment]
Note, thanks. Closing this.
